In [1]:
import torch
torch.__version__

'2.1.2.post303'

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

In [8]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad
# from the 10 min doc on tensor exercice

tensor([[ 2., -2.],
        [ 2.,  2.]])

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.shape

torch.Size([])

In [14]:
int_from_scalar = scalar.item()
int_from_scalar

7

A vector is a single dimension tensor but can contain many numbers.

In [15]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ( [ ) and you only need to count one side.

In [18]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

When the first rank is higher than the second (3, 2), its a higher-dimensional tensor.
Matrice is often used to define a rank-2 tensor with two equal dimension, but basically they all can be refered as a tensor

In [21]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Tensor can represent almost anything, first row could be day of the week, snd could bbe steak sales, trd could me almond butter sales

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR.ndim

3

1 dimension of 3 by 3

In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

Tensor are basically when there is multiples dimensions of matrices (3, 3, 3)

In [24]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.5326, 0.5352, 0.0033, 0.1846],
         [0.9410, 0.0705, 0.2008, 0.3463],
         [0.5243, 0.8211, 0.0576, 0.4913]]),
 torch.float32)

In [25]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
random_image_size_tensor

tensor([[[0.2052, 0.6004, 0.7202],
         [0.7979, 0.3628, 0.6645],
         [0.9539, 0.9038, 0.0342],
         ...,
         [0.5378, 0.5794, 0.1041],
         [0.1811, 0.9960, 0.8762],
         [0.8865, 0.7775, 0.7062]],

        [[0.0153, 0.2631, 0.6181],
         [0.5503, 0.5494, 0.2004],
         [0.1290, 0.3686, 0.4253],
         ...,
         [0.8024, 0.3706, 0.2126],
         [0.6861, 0.8002, 0.2603],
         [0.1912, 0.2645, 0.4407]],

        [[0.9306, 0.0800, 0.2869],
         [0.0044, 0.7270, 0.9442],
         [0.9927, 0.9040, 0.7381],
         ...,
         [0.6263, 0.7559, 0.3630],
         [0.3406, 0.2156, 0.3027],
         [0.7415, 0.8358, 0.2161]],

        ...,

        [[0.4976, 0.1631, 0.9708],
         [0.3068, 0.7845, 0.7598],
         [0.3811, 0.1952, 0.5948],
         ...,
         [0.9786, 0.9677, 0.1044],
         [0.5374, 0.5927, 0.5220],
         [0.1230, 0.3933, 0.5625]],

        [[0.0942, 0.0673, 0.4279],
         [0.5942, 0.7212, 0.3334],
         [0.

In [28]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [29]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [32]:
zero_to_ten_deprecated = torch.arange(0,10)
zero_to_ten_deprecated

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
ten_zeros = torch.zeros_like(zero_to_ten_deprecated) #zeros_like is the data, (zero_to_ten..) is the input shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use

In [38]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [39]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [40]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8878, 0.8821, 0.7122, 0.2653],
        [0.2106, 0.1166, 0.4197, 0.3480],
        [0.6399, 0.2031, 0.8593, 0.0933]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where"

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

In [41]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor # don't change unless reassigned

tensor([1, 2, 3])

In [47]:
tensor - 10

tensor([-9, -8, -7])

In [48]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [49]:
sub_tensor = tensor - 10
sub_tensor

tensor([-9, -8, -7])

In [50]:
tensor + 10

tensor([11, 12, 13])

In [51]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [52]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


The main two rules for matrix multiplication to remember are:

    The inner dimensions must match:
        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work

    The resulting matrix has the shape of the outer dimensions:
        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

In [54]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])