In [1]:
import torch

In [3]:
random = torch.rand((7,7))
random

tensor([[0.4489, 0.6305, 0.9445, 0.1950, 0.3411, 0.5630, 0.5233],
        [0.3570, 0.1628, 0.9689, 0.1841, 0.2267, 0.2517, 0.7572],
        [0.2329, 0.0466, 0.6109, 0.0356, 0.3347, 0.5779, 0.9391],
        [0.1994, 0.5098, 0.6503, 0.9984, 0.0305, 0.1588, 0.6759],
        [0.5224, 0.5938, 0.3757, 0.8112, 0.4245, 0.1234, 0.3246],
        [0.6960, 0.4162, 0.6173, 0.1609, 0.9605, 0.9437, 0.8801],
        [0.9202, 0.5508, 0.4883, 0.8972, 0.4608, 0.2022, 0.7536]])

In [5]:
random_2 = torch.rand(1,7)
random_2

tensor([[0.1412, 0.7271, 0.9101, 0.7922, 0.1833, 0.7309, 0.8735]])

In [6]:
random @ random_2.T

tensor([[2.4670],
        [2.0834],
        [1.9551],
        [2.4938],
        [1.9416],
        [2.7247],
        [2.5760]])

In [7]:
torch.manual_seed(0)

tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1, 7)
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [8]:
torch.cuda.manual_seed(1234)

In [19]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [11]:
tensor_AB = tensor_A @ tensor_B.T
tensor_AB

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [14]:
print(tensor_AB.min())
print(tensor_AB.max())

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')


In [15]:
print(tensor_AB.argmax(), tensor_AB.argmin())

tensor(3, device='cuda:0') tensor(0, device='cuda:0')


In [18]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
tensor_permuted = tensor.reshape(10) # tensor.squeeze() since it basically remove all the 1 dim
tensor, tensor_permuted

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))